### ISSUE TITLE
native plugin (aka javalib.cmxs)

### ISSUE THREAD

**Issue by vprevosto** [javalib-team/javalib#20]
In order to ease the use of javalib in dynamically loaded code, I was looking to extend the compilation to create a `.cmxs` and update the `META` file accordingly, and I noticed that there was some support, which has mostly been commented out around 10 years ago in commit 7ebc131884db1fd61. Is the reason that led to this decision still relevant nowadays, or would a PR restoring this feature stand a chance of being merged at some point?

**Comment by davidpichardie** [comment]
Hi Virgile,

I would be interested in your PR. Please propose us a clear test case to better understand the feature and test it.

David

**Comment by vprevosto** [comment]
OK, thanks for the clarification. Just another quick question though: it seems that the latest version, 3.2.1, is on branch `remove_extlib_dep`. Should I base my modifications on it rather than on `master`?
